name: Create Package
inputs:
  arch:
    description: Architecture
    required: true
outputs:
  package-name:
    description: Package name
    value: ${{steps.create-package.outputs.package-name}}
runs:
  using: composite
  steps:
  - id: create-package
    # XXX: Should use github.action_path here, but it’s currently broken in
    #      container builds, see https://github.com/actions/runner/issues/716
    run: ../util/create-package.sh "${{github.run_number}}-$(date +%F)" "${{runner.os}}" "${{inputs.arch}}"
    working-directory: build
    shell: bash
    env:
      RUNNER_OS: ${{runner.os}}
      INPUT_ARCH: ${{inputs.arch}}
